site_name: CloudAwan Documents

pages:
- Home: 'index.md'
- Getting Started:
    - 'Quick Start Guide': 'getting_started_with_cloudawan/quick_start_guide.md'
#    - 'Terminologies': 'getting_started_with_cloudawan/terminologies.md'
- Install Guide:
    - 'Deploying Cluster': 'install_guide/deploying_cluster.md'
    - 'Deploying In AWS': 'install_guide/deploying_in_aws.md'
- Architecture:
    - 'Overview': 'architecture/overview.md'
#    - 'Infrastructure': 'architecture/infrastructure.md'
    - 'Deployment Concept': 'architecture/deployment_concept.md'
#    - 'Management Concept': 'architecture/management_concept.md'
#- About:
#    - 'License': 'about/license.md'
#    - 'Release Notes': 'about/release_notes.md'

theme: readthedocs
