site_name: CloudAwan Documents

pages:
- Home: 'index.md'
- Getting Started With CloudAwan:
    - 'Quick Start Guide': 'getting-started-with-cloudawan/quick-start-guide.md'
    - 'Terminologies': 'getting-started-with-cloudawan/terminologies.md'
    - 'Architecture': 'getting-started-with-cloudawan/architecture.md'
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'

theme: readthedocs
